### ISSUE TITLE
Quelques recommandations comme ça...

### ISSUE THREAD

**Issue by NerOcrO** [ghsdl/canyounameit#1]
Salut !
J'ai vu que tu partageais ton site sur Twitter et j'ai eu envie de te faire quelques recommandations car j'aurai bien voulu qu'on m'en fasse à mes débuts. Tu en feras ce que tu veux :)

> package.json

- Tu peux mettre dans la partie `devDependencies` les modules qui ne servent pas pour le build, ça fonctionne tout de même bien comme tu as fait mais je trouve que ça sépare bien les modules de la production des outils ;
- J'ai tendance à séparer les choses donc la configuration `eslint`, je la met dans un fichier à part : side effect, quand quelqu'un modifie la configuration `eslint`, tu auras des `diff` sur ce fichier en question et non pas dans `package.json` donc plus auto portant ;
- Il manque une commande pour lancer le type checking ;
- Il manque une commande pour lancer le linter ;
- Tu as 33 vulnérabilités sur ton projet, tu peux les voir en faisant `npm audit`.

> Fichiers tsx

- Convention collective : mettre des `""` à la place des `''` pour les attributs `html` ;
- Convention collective : ne pas mettre de majuscule dans un nom de classe CSS ;
- Tu peux directement mettre `export const ...` et ainsi gagner une ligne de code et surtout éviter de l'appeler différement à l'`import`, cela m'a déjà posé des problèmes de compréhension, je pensais trouver par exemple `App` alors que c'était marqué `import MySuperApp from ./App` .

> Fichiers scss

- Trier les propriétés par ordre alphabétique, pourquoi ? car c'est le "rangement" que tous les humains connaissent par défaut et le cerveau va vite le détecte, tu réduis la charge cognitive.

> App.tsx

- Au lieu d'importer `name`, tu aurais pu faire un [hook custon](https://reactjs.org/docs/hooks-custom.html) ;
- Tu peux supprimer le fichier `components/index.tsx`, il ne sert à rien et tu peux importer les trois composants directement et tu enleves un peu de charge cognitive.

> interfaces.tsx

- Tu pourrais mettre l'interface au plus proche du composant comme ça, quand tu supprimes le composant, tu supprimes defacto son interface, cela évite du code mort (et tu supprimes encore une ligne d'import).

> Icons.tsx

- Pourquoi ne pas avoir mis en props l'icon directement plutôt qu'une chaîne de caractères (ce que tu as très bien fait avec `onClick`) ? Parce que du coup, ton composant est fortement lié à tous les icons que tu as, quand tu vas en rajouter un, il faudra modifier ce composant alors que c'est juste un wrapper au final. De maniète général, un composant graphique doit être bête, c'est-à-dire qu'il ne doit presque pas avoir de logique ;
- De plus, ton enchaînement de tenaire fait mal à la tête :p.

> Paragraph.tsx

- C'est préférable d'utiliser `children` quand tu veux insérer du html dans un composant car c'est auto portant.

Ton code est tout à fait correct, lisible et surtout fonctionnel ! J'ai juste voulu partager mon savoir et expérience avec toi.
N'hésite pas à rebondir ou poser des questions si je n'ai pas été assez clair.

**Comment by ghsdl** [comment]
Hello 🤓 ! 

C'est gentil d'avoir pris le temps d'avoir fait un retour si détaillé et dans la bienveillance! J'ai quelques questions, et quelques remarques.
> package.json

- les modules qui ne servent pas pour le build : comment identifier lesquels servent précisément pour le build et les autres non ? cette information est-elle "visible" ou "disponible" dans mon projet ou faut le déduire "tout simplement" ? 🧐


- la commande pour lancer le type checking c'est "tsc" ? 

- j'ai effectivement pas mal de vulnérabilités, je suis redescendue à 15 après un npm audit et son cousin le --force 😩 

> Fichiers scss

- ah c'est intéressant cette remarque, je trouve plus simple de faire dans l'ordre des classes dans le fichier de haut en bas 😄 je pense que si je changeais maintenant, ça serait ça la charge cognitive 🙈

> App.tsx

- je n'ai pas encore pratiqué les hooks custom, ça sera carrément l'occasion !

> interfaces.tsx

- typescript ayant tendance à nous crier dessus dès qu'il reconnaît pas un typage, je préfère séparer mes interfaces pour garder des composants le plus "clean" possible en termes de React. Peut-être car je ne suis pas encore habituée à coder tout le temps avec TS et que c'est un peu déconcertant au début tout ce charabia.

> Icons.tsx

- j'aurais effectivement pu passer icon en props comme onClick. Ma réflexion a été la suivante: admettons j'ai un icon que j'utilise beaucoup, sur un gros projet forcément. D'un coup je décide que le design de l'arrow up me convient plus et il est littéralement partout cet icon... faudrait que je change l'icone dans TOUS les fichiers où il est importé alors qu'avec mon composant qui les gère je le change une fois et ça se répercute partout sur l'appli. Je sais pas si ça fait sens mais en passant la string je sais qu'elle, elle a moins de chance de changer 😅 Pour le ternaire, je comprends ton point de vue c'est indigeste.

>Paragraph.tsx 

- y a-t-il une raison à cette préférence ? de meilleures performances ou tout simplement une convention ?

C'est cool si le code est lisible c'est important, n'hésite pas si tu as d'autres remarques !

**Comment by NerOcrO** [comment]
>     * les modules qui ne servent pas pour le build : comment identifier lesquels servent précisément pour le build et les autres non ? cette information est-elle "visible" ou "disponible" dans mon projet ou faut le déduire "tout simplement" ? 🧐
Tu mets dans `dependencies` ce dont ton site a besoin pour s'afficher. Tu mets dans `devDependencies` les outils du type linter, ts, @types, sass.
>     * la commande pour lancer le type checking c'est "tsc" ?
C'est ça !
>     * j'ai effectivement pas mal de vulnérabilités, je suis redescendue à 15 après un npm audit et son cousin le --force 😩
Good! c'est une habitude à avoir, tu peux regarder de temps en temps et github te le dira aussi.
>     * ah c'est intéressant cette remarque, je trouve plus simple de faire dans l'ordre des classes dans le fichier de haut en bas 😄 je pense que si je changeais maintenant, ça serait ça la charge cognitive 🙈
Et tu as bien raison mais je ne parlais pas de ça ;) je parlais des propriétés c'est-à-dire width, margin...
>     * typescript ayant tendance à nous crier dessus dès qu'il reconnaît pas un typage, je préfère séparer mes interfaces pour garder des composants le plus "clean" possible en termes de React. Peut-être car je ne suis pas encore habituée à coder tout le temps avec TS et que c'est un peu déconcertant au début tout ce charabia.
Tu te confrontes à deux avis divergeants qui ont chacun leur point de vue, à toi de décider ce qui est mieux pour toi pour le moment mais de garder en tête l'autre point de vue aussi. Quand tu seras en équipe, il faudra trancher pour une des deux et ça sera potentiellement pas la tienne, ce qu'on appelle les standards d'équipe.
>     * j'aurais effectivement pu passer icon en props comme onClick. Ma réflexion a été la suivante: admettons j'ai un icon que j'utilise beaucoup, sur un gros projet forcément. D'un coup je décide que le design de l'arrow up me convient plus et il est littéralement partout cet icon... faudrait que je change l'icone dans TOUS les fichiers où il est importé alors qu'avec mon composant qui les gère je le change une fois et ça se répercute partout sur l'appli. Je sais pas si ça fait sens mais en passant la string je sais qu'elle, elle a moins de chance de changer 😅 Pour le ternaire, je comprends ton point de vue c'est indigeste.
Oui je vois très bien ce que tu veux dire mais on commence à toucher une notion pas simple à intégrer au début, c'est la notion d'abstraction et le fait qu'un composant graphique doit juste afficher des trucs avec un minimum de complexité. En l'occurence, ton fichier icon est juste un wrapper d'icon mais il ne doit pas connaitre l'icon. Du coup, pour palier à ton problème, il te faudrait un autre composant graphique (abstraction) qui appelerait icon avec en props la bonne icone et dans tes composants "parents", tu appelles ce nouveau composant. En espérant avoir été clair ? :p
>     * y a-t-il une raison à cette préférence ? de meilleures performances ou tout simplement une convention ?
https://reactjs.org/docs/jsx-in-depth.html#children-in-jsx
Mieux vaut utiliser les props pour de la donnée et si tu as du HTML, autant le mettre en mode HTML.

Jvais pas forcément ajouter d'autres remarques car je l'ai fait de façon opportuniste et jvais surement aller aider d'autres jeunes développeurs-euses vu que vous partagez à gogo sur Twitter :p
Par contre, si tu veux faire du pair programming ou de la code review, n'hésite pas à me contacter sur twitter (j'ai le même pseudo) et on se fait une visio. Rien d'obligatoire évidemment, je teste de nouveaux formats de transmission de savoir autre que les vidéos ou blogs qui ne m'interessent pas vraiment.
